appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: bMD1T2KY11UGIjrp8V1+rifdVervpJr9NnPYGweB6Ceon0rWheCNLOyZc81URpZdVtcDrtzgM+UdMxfmm8qHDAKrBASmDnhWPUhgeRWAcUGDZ0AlofwRwoTxtR3XuYAU1wYGKDCWk1gpMt40mo2Kb2MVZlm0zHuJPyMgAab/ibdXqnLNkNuWaGJ4bSQSkqD4eTf08cW8Fyz3Js++l5pce9fXd66eaAcJ9Ah+dglPhVzeoFxnYspqnXJhJ8GEC+RoG2C1ym1WHTa2YK8m4udqPWNebnOIooNK+iCsUzDVQB+V1ElIN5Uf8vkoxSxuiSQCy7CVcJoXxHKsL/yzsje0XfSUH2BuhmlnHqxj3hxBnaW2HXmOLKQXoaloEjByDXnniOkw3IF7QEF2l8xHuObm4egd14YC31IkPwmnoxE5j7JZZ142lcNHN6bwfcYkAphejWy+yJKG1jEg/52zKEog0DLuaHt7tuWWid9yvgDSds9z5CtAAPSyXVQKj1SyOY96wlftsONtDc3c9IhYeLb99UPzaFuA0i2uSD5p+rr8ReFCJcFNcJZZlFkQ4V098QsFA5m5a4t1ymPYMOPswyURteF6Tv85aBlrFy3VIKKG3rinP3bpaObEpnY+ZiCcs5piz0HTXDCfwQQ5lC5wa2OOIM8W8t6cepCbQxm4N/Ndzfo=
conda_forge_output_validation: false
